config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :questions do
    resources :answers, only: [:create, :new]
  end

  resources :answers do
    resources :likes
  end
  
  patch 'questions/:question_id/answers/:id', :to => 'answers#accept'
  get 'users/:user_id/likes/', :to => 'likes#index_user_likes'

  resources :users, only: [:index, :show, :update, :avatar]
  post 'users/:id/avatars/', :to => 'users#avatar'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, :presence => true

  before_create :create_if_user_has_enough_points, :remove_user_points

  private
    def create_if_user_has_enough_points
      if self.user.points < User::POINTS_QUESTION_COST
        self.errors.add(:base, I18n.t('question.not_enough_points_error'))
        return false
      end
      true
    end

    def remove_user_points
      self.user.remove_points(User::POINTS_QUESTION_COST)
      true
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action only: [:update, :destroy] do
    check_resource_owner!(current_user, @question.user)
  end

  def index
    respond_to do |format|
      format.json { render :json => Question.all.to_json(:include => { :user => { :only => [:name ]} }) }
    end
  end

  def show
    respond_to do |format|
      format.json { 
        render :json => @question.to_json(
          :include => { 
            :answers => { 
              :methods => [:likes_count] 
            },
            :user => { 
              :only => [:name],
              :methods => [:avatar_thumb_url]
            },
          }
        ) 
      }
    end
  end

  def new
    respond_to do |format|
      format.json { render :json => Question.new }
    end
  end

  def edit
    respond_to do |format|
      format.json { render :json => @question.to_json }
    end
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      respond_to do |format|
        format.json { render :json => { message: t('question.create_success') }.to_json, :status => 201 }
      end
    else
      respond_to do |format|
         format.json { render :json => { :errors => @question.errors.full_messages }, :status => 400 }
      end
    end
  end

  def update
    if @question.update(question_params)
      respond_to do |format|
        format.json { render :json => { message: t('question.update_success') }.to_json }
      end
    else
      respond_to do |format|
         format.json { render :json => { :errors => @question.errors.full_messages }, :status => 400 }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.json { render :json => { message: t('question.delete_success') }.to_json, :status => 204 }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:title, :contents)
  end
end

app/views/questions/_details.html.slim
.details
  '  Created on
  = l(question.created_at, format: :long)
  '  by
  = link_to question.user, user_path(question.user)

app/views/questions/_form.html.slim
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h2 = "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      ul
        - @question.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :contents
    = f.text_area :contents
  .actions= f.submit 'Save'

app/views/questions/_question.html.slim
.question id="question-#{question.id}"
  .title= link_to question.title, question_path(question)
  = render "questions/details", question: question

app/views/questions/edit.html.slim
h1 Editing question

== render 'form'

= link_to 'Show', @question
'|
= link_to 'Back', questions_path

app/views/questions/index.html.slim
h1 Questions

= render @questions

= link_to 'New Question', new_question_path

app/views/questions/new.html.slim
h1 New question

== render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
.question id="question-#{@question.id}"
  h2= @question.title

  = render "details", question: @question

  p
    = @question.contents

  .links
    = link_to 'Edit', edit_question_path(@question)
    '  |
    = link_to 'Delete', question_path(@question, method: :delete)

  h3 Answers

  - if @question.answers.any?
    = render @question.answers
  - else
    '  There are no answers to this question.

  h3 Add answer

  = form_for [@question, @answer] do |f|

    .field
      = f.label :contents
      = f.text_area :contents

    .actions= f.submit 'Save'